// Code generated by MockGen. DO NOT EDIT.
// Source: channels/url_executor_provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	channels "github.com/naviud/webpage-analyzer/channels"
)

// MockUrlExecutorProvider is a mock of UrlExecutorProvider interface.
type MockUrlExecutorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUrlExecutorProviderMockRecorder
}

// MockUrlExecutorProviderMockRecorder is the mock recorder for MockUrlExecutorProvider.
type MockUrlExecutorProviderMockRecorder struct {
	mock *MockUrlExecutorProvider
}

// NewMockUrlExecutorProvider creates a new mock instance.
func NewMockUrlExecutorProvider(ctrl *gomock.Controller) *MockUrlExecutorProvider {
	mock := &MockUrlExecutorProvider{ctrl: ctrl}
	mock.recorder = &MockUrlExecutorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlExecutorProvider) EXPECT() *MockUrlExecutorProviderMockRecorder {
	return m.recorder
}

// Provide mocks base method.
func (m *MockUrlExecutorProvider) Provide() channels.UrlExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provide")
	ret0, _ := ret[0].(channels.UrlExecutor)
	return ret0
}

// Provide indicates an expected call of Provide.
func (mr *MockUrlExecutorProviderMockRecorder) Provide() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provide", reflect.TypeOf((*MockUrlExecutorProvider)(nil).Provide))
}
